/**
 * Structured error codes for programmatic handling by SDK consumers.
 */
export enum SDKErrorCode {
  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT = 'TIMEOUT',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
  INVALID_CONFIGURATION = 'INVALID_CONFIGURATION',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_RESPONSE = 'INVALID_RESPONSE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  SSL_REQUIRED = 'SSL_REQUIRED',
  RATE_LIMIT = 'RATE_LIMIT',
  API_ERROR = 'API_ERROR',
  UNKNOWN = 'UNKNOWN',
}
